import { readFile } from "node:fs/promises"; import { assert, pass } from "./test-helpers.mjs"; const content=await readFile(new URL("../content.js",import.meta.url),"utf8"); const provider=await readFile(new URL("../provider-core.js",import.meta.url),"utf8");
for(const token of ["DAG_RUN_IMAGE_JOB","DAG_RECONCILE","DAG_ADVANCE_ATTEMPT","OUTPUT_AMBIGUOUS","ATTEMPT_ID_MISMATCH","SECURITY_BLOCKER","AMBIGUOUS_MULTIPLE_OUTPUTS"]) assert.ok((content+provider).includes(token),token); assert.ok(!/\.click\(\)[\s\S]{0,300}\.click\(\)/.test(content),"no blind double-click retry"); assert.ok(provider.includes('data-message-author-role="assistant"')); assert.ok(!content.includes("captcha.click"));
assert.ok(content.includes("function attachmentFingerprint(before, expected, input)"), "ATTACHMENT_NOT_READY must capture the real DOM shape for diagnosis");
assert.ok(content.includes(String.raw`detail.failure_type = "ATTACHMENT_NOT_READY"`), "the diagnostic error must keep a clean failure_type so classifyFailure and retryDecision still work");
assert.ok(content.includes("failure_type: error.failure_type || error.message"), "a diagnostic-carrying error must not leak its payload into failure_type");
assert.ok(content.includes("input_files:"), "the fingerprint must report whether the file input was actually populated");
const stageAt = content.indexOf("await stageReferences(");
const typeAt = content.indexOf("setComposerText(target, String(message.prompt");
const confirmAt = content.indexOf("await confirmReferences(staged)");
const sendAt = content.indexOf(String.raw`, 7000, "SEND_NOT_READY"`);
assert.ok(stageAt > 0 && typeAt > 0 && confirmAt > 0 && sendAt > 0, "runImageJob must stage, type, confirm and only then resolve Send");
assert.ok(stageAt < typeAt, "references are staged before the prompt is typed");
assert.ok(typeAt < confirmAt, "the prompt is typed while the page ingests the upload, so a detection failure no longer hides whether typing works");
assert.ok(confirmAt < sendAt, "attachment confirmation must still gate Send: never submit without its verified reference");
assert.ok(!content.includes("Core.SELECTORS.attachmentPreview.reduce("), "summing overlapping selectors across the document is not a count of attachments");
assert.ok(content.includes("function attachmentNodes(scope = attachmentScope())"), "previews must be observed as unique nodes inside the composer, not counted document-wide");
assert.ok(content.includes("function attachmentPending(scope)"), "the busy latch must be scoped so an unrelated page-wide spinner cannot pin it true forever");
assert.ok(content.includes("Decisions.addedSince(staged.before, attachmentNodes(scope))"), "readiness must be decided on newly arrived previews");
pass("content adapter: messages, reconciliation, blockers and no blind resend");
